### ISSUE TITLE
Slope finishing abruptly 

### ISSUE THREAD

**Issue by Pypadopoulos** [MBR111/CivilEng#2]
When the Reservoir tool is used, slope stars correctly from poliline marked and starts the slope at selected ratio (1:H). But suddenly, when slope reaches 100 meters each side in plan view, it descends abruptly to the terrain. I tried in several locations obtaining the same result. Lake is obtained correctly.

Two figures are attatched to ilustrate the problem.

![ModifiedTerrain](https://github.com/MBR111/CivilEng/assets/120091818/034254ad-a2e4-4b59-9b59-52817c28d9f1)
![OriginalTerrain](https://github.com/MBR111/CivilEng/assets/120091818/e1751d67-c1ba-4d08-a0df-4e109cc02e50)

INPUT: ({ 'DEM' : 'XXXX/Test-MDT-Migas.tif', 'dam_top_level' : 400, 'dam_vector_layer' : 'C:/Users/RVV/Desktop/Test-LIN.shp', 'dam_wall_slope' : 3, 'new_DEM_raster' : 'TEMPORARY_OUTPUT', 'new_lake_raster' : 'TEMPORARY_OUTPUT', 'reservoir_inner_point' : '576415.550627,4132294.982787 [EPSG:3042]', 'water_depth_from_top' : 5 })

**Comment by Pypadopoulos** [comment]
Same issue is had with the Earthworks tool:
![Uploading ModifiedTerrain2.png…]()

**Comment by Pypadopoulos** [comment]
Same issue is had with the Earthworks tool (tried with a full-slope earthwork) :
![ModifiedTerrain2](https://github.com/MBR111/CivilEng/assets/120091818/2825a804-99b5-4196-954c-6953d7634f4b)
{ 'DEM' : 'XXXX/Test-MDT-Migas.tif', 'cut_slope' : 1, 'fill_slope' : 3, 'new_DEM' : 'TEMPORARY_OUTPUT', 'platform' : 'C:/Users/RVV/Desktop/Platform.shp', 'platform_level' : 400 }

**Comment by MBR111** [comment]
> When the Reservoir tool is used, slope stars correctly from poliline marked and starts the slope at selected ratio (1:H). But suddenly, when slope reaches 100 meters each side in plan view, it descends abruptly to the terrain. I tried in several locations obtaining the same result. Lake is obtained correctly.
> 
> Two figures are attatched to ilustrate the problem.
> 
> ![ModifiedTerrain](https://user-images.githubusercontent.com/120091818/268981344-034254ad-a2e4-4b59-9b59-52817c28d9f1.png) ![OriginalTerrain](https://user-images.githubusercontent.com/120091818/268981348-e1751d67-c1ba-4d08-a0df-4e109cc02e50.png)
> 
> INPUT: ({ 'DEM' : 'XXXX/Test-MDT-Migas.tif', 'dam_top_level' : 400, 'dam_vector_layer' : 'C:/Users/RVV/Desktop/Test-LIN.shp', 'dam_wall_slope' : 3, 'new_DEM_raster' : 'TEMPORARY_OUTPUT', 'new_lake_raster' : 'TEMPORARY_OUTPUT', 'reservoir_inner_point' : '576415.550627,4132294.982787 [EPSG:3042]', 'water_depth_from_top' : 5 })



> When the Reservoir tool is used, slope stars correctly from poliline marked and starts the slope at selected ratio (1:H). But suddenly, when slope reaches 100 meters each side in plan view, it descends abruptly to the terrain. I tried in several locations obtaining the same result. Lake is obtained correctly.
> 
> Two figures are attatched to ilustrate the problem.
> 
> ![ModifiedTerrain](https://user-images.githubusercontent.com/120091818/268981344-034254ad-a2e4-4b59-9b59-52817c28d9f1.png) ![OriginalTerrain](https://user-images.githubusercontent.com/120091818/268981348-e1751d67-c1ba-4d08-a0df-4e109cc02e50.png)
> 
> INPUT: ({ 'DEM' : 'XXXX/Test-MDT-Migas.tif', 'dam_top_level' : 400, 'dam_vector_layer' : 'C:/Users/RVV/Desktop/Test-LIN.shp', 'dam_wall_slope' : 3, 'new_DEM_raster' : 'TEMPORARY_OUTPUT', 'new_lake_raster' : 'TEMPORARY_OUTPUT', 'reservoir_inner_point' : '576415.550627,4132294.982787 [EPSG:3042]', 'water_depth_from_top' : 5 })

Hi there,

This particular issue can be solved editing the file "Reservoir_algorithm.py" in the Qgis plugin folder located under your Qgis profile directory (you can open it directly from Qgis) and changing the line  'RINGS': 1000, to  'RINGS': 10000,

Try it and please come back to me if it doesn't solve your problem.

**Comment by MBR111** [comment]
> Same issue is had with the Earthworks tool (tried with a full-slope earthwork) : ![ModifiedTerrain2](https://user-images.githubusercontent.com/120091818/268983137-2825a804-99b5-4196-954c-6953d7634f4b.png) { 'DEM' : 'XXXX/Test-MDT-Migas.tif', 'cut_slope' : 1, 'fill_slope' : 3, 'new_DEM' : 'TEMPORARY_OUTPUT', 'platform' : 'C:/Users/RVV/Desktop/Platform.shp', 'platform_level' : 400 }

Hi there,

This particular issue can be solved editing the file "Earthworks_algorithm.py" in the Qgis plugin folder located under your Qgis profile directory (you can open it directly from Qgis) and changing the line 'RINGS': 100, to 'RINGS': 1000, or a value higher than the planar extents of the earthwork (you should try with differents values).

Try it and please come back to me if it doesn't solve your problem.
